import type { Track } from '../types/dj';

// Generate synthetic waveform peaks (bass, mid, treble intensities)
export function generateWaveformPeaks(count = 200, seed = 1): number[] {
  const peaks: number[] = [];
  for (let i = 0; i < count; i++) {
    const t = i / count;
    const envelope = Math.sin(t * Math.PI);
    const noise = Math.sin(i * 0.3 * seed) * 0.3 + Math.cos(i * 0.7 + seed) * 0.2;
    const beatPulse = (i % 4 === 0) ? 0.35 : 0.05;
    const val = Math.max(0.08, Math.min(1.0, (0.4 + noise + beatPulse) * (0.6 + envelope * 0.5)));
    peaks.push(parseFloat(val.toFixed(3)));
  }
  return peaks;
}

export const INITIAL_TRACKS: Track[] = [
  {
    id: 'trk-1',
    filename: 'Club_Beat_128BPM.wav',
    title: 'Club Beat (128 BPM Bass Groove)',
    artist: 'Antigravity Studio',
    duration: 30.0,
    format: 'WAV',
    fileLocation: 'demo-music/Club_Beat_128BPM.wav',
    url: '/demo-music/Club_Beat_128BPM.wav',
    bpm: 128.0,
    key: '8A',
    musicalKeyName: 'A Minor',
    energy: 0.92,
    genre: 'EDM / Club',
    filePath: 'G:/DJ APP/demo-music/Club_Beat_128BPM.wav',
    status: 'analyzed',
    introTime: 4.0,
    outroTime: 26.0,
    loudness: -6.5,
    waveformPeaks: generateWaveformPeaks(200, 1),
  },
  {
    id: 'trk-2',
    filename: 'Harmonic_Synths_120BPM.mp3',
    title: 'Harmonic Synths (120 BPM Chords)',
    artist: 'Antigravity Studio',
    duration: 30.0,
    format: 'MP3',
    fileLocation: 'demo-music/Harmonic_Synths_120BPM.mp3',
    url: '/demo-music/Harmonic_Synths_120BPM.mp3',
    bpm: 120.0,
    key: '7B',
    musicalKeyName: 'C Major',
    energy: 0.85,
    genre: 'Synth Melodic',
    filePath: 'G:/DJ APP/demo-music/Harmonic_Synths_120BPM.mp3',
    status: 'analyzed',
    introTime: 4.0,
    outroTime: 26.0,
    loudness: -7.0,
    waveformPeaks: generateWaveformPeaks(200, 2),
  },
  {
    id: 'trk-3',
    filename: 'Ring01.wav',
    title: 'Ring 01 (Windows Bell Theme)',
    artist: 'Microsoft Audio',
    duration: 5.6,
    format: 'WAV',
    fileLocation: 'demo-music/Ring01.wav',
    url: '/demo-music/Ring01.wav',
    bpm: 120.0,
    key: '9A',
    musicalKeyName: 'E Minor',
    energy: 0.65,
    genre: 'Acoustic / Chimes',
    filePath: 'G:/DJ APP/demo-music/Ring01.wav',
    status: 'analyzed',
    introTime: 0.5,
    outroTime: 5.0,
    loudness: -10.2,
    waveformPeaks: generateWaveformPeaks(200, 3),
  },
  {
    id: 'trk-4',
    filename: 'Alarm01.wav',
    title: 'Alarm 01 (Rhythmic Pulse)',
    artist: 'Microsoft Audio',
    duration: 5.5,
    format: 'WAV',
    fileLocation: 'demo-music/Alarm01.wav',
    url: '/demo-music/Alarm01.wav',
    bpm: 130.0,
    key: '8A',
    musicalKeyName: 'A Minor',
    energy: 0.78,
    genre: 'Electronic Pulse',
    filePath: 'G:/DJ APP/demo-music/Alarm01.wav',
    status: 'analyzed',
    introTime: 0.5,
    outroTime: 5.0,
    loudness: -8.5,
    waveformPeaks: generateWaveformPeaks(200, 4),
  },
  {
    id: 'trk-5',
    filename: 'tada.wav',
    title: 'Ta-Da (Fanfare Brass)',
    artist: 'Microsoft Audio',
    duration: 1.6,
    format: 'WAV',
    fileLocation: 'demo-music/tada.wav',
    url: '/demo-music/tada.wav',
    bpm: 110.0,
    key: '1B',
    musicalKeyName: 'B Major',
    energy: 0.88,
    genre: 'Stab / Fanfare',
    filePath: 'G:/DJ APP/demo-music/tada.wav',
    status: 'analyzed',
    introTime: 0.1,
    outroTime: 1.5,
    loudness: -6.0,
    waveformPeaks: generateWaveformPeaks(200, 5),
  },
  {
    id: 'trk-6',
    filename: 'chimes.wav',
    title: 'Chimes (Harmonic Bells)',
    artist: 'Microsoft Audio',
    duration: 1.2,
    format: 'WAV',
    fileLocation: 'demo-music/chimes.wav',
    url: '/demo-music/chimes.wav',
    bpm: 100.0,
    key: '11B',
    musicalKeyName: 'A Major',
    energy: 0.60,
    genre: 'Chime FX',
    filePath: 'G:/DJ APP/demo-music/chimes.wav',
    status: 'analyzed',
    introTime: 0.1,
    outroTime: 1.1,
    loudness: -9.0,
    waveformPeaks: generateWaveformPeaks(200, 6),
  }
];
